name: Auto PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node 16 compatibility

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

      - name: Check for Changes Between Develop and Main
        id: changes
        run: |
          git fetch origin main
          if git diff --quiet develop origin/main; then
            echo "No changes detected between develop and main."
            exit 0
          else
            echo "Changes detected between develop and main."
          fi

      - name: Create Pull Request from Develop to Main
        if: steps.changes.outcome == 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Sync Develop with Main"
          body: |
            This pull request was automatically generated to sync changes from the `develop` branch into the `main` branch.
          branch: auto-pr/develop-to-main
